name: Lint | Test | Build
on:
  push:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
      - develop
      - staging
    paths-ignore:
      - '*.md'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - name: Eslint
        run: yarn lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - name: Prettier
        run: yarn prettier . --check

  test:
    name: Unit & Integration tests
    needs:
      - eslint
      - prettier
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - name: Run jest with CI option
        run: yarn test:ci

  acceptance:
    name: Smoke & Acceptance tests
    runs-on: ubuntu-latest
    needs:
      - eslint
      - prettier
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build:storybook --quiet
      - name: Smoke & Acceptance tests
        run: yarn test:acceptance

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
      - acceptance
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Build NextJS App
        run: yarn build
